#------------------------
# Header / Menu, evenutally

menu:
- {text: 'KONSEPTET', anchor: 'concept'}
- {text: 'BOOKING', anchor: 'booking'}
- {text: 'ØKONOMI', anchor: 'money'}
- {text: 'UTSTYR', anchor: 'gear'}
- {text: 'BIDRA', anchor: 'contribute'}

#------------------------
# Footer

social:
- {icon: 'instagram', link: 'https://www.instagram.com/becco_oslo/'}
- {icon: 'facebook', link: 'https://www.facebook.com/oslobecco'}

#------------------------
seo:
  description: 'mandagsklubben-oslo'
  #rel-author: 'https://plus.google.com/u/0/#'
  #rel-publisher: 'https://plus.google.com/u/0/#'

