#------------------------
# Header / Menu, evenutally

#------------------------
# Footer

social:
- {icon: 'instagram', link: ''}
- {icon: 'youtube',   likk: ''}

#------------------------
seo:
  description: 'mandagsklubben-oslo'
  #rel-author: 'https://plus.google.com/u/0/#'
  #rel-publisher: 'https://plus.google.com/u/0/#'

